#ifndef DataFormats_Phase2ITBitStreamSoA_interface_Phase2ITModuleMapHost_h
#define DataFormats_Phase2ITBitStreamSoA_interface_Phase2ITModuleMapHost_h

#include "DataFormats/Phase2ITBitStreamSoA/interface/Phase2ITModuleMapSoA.h"
#include "DataFormats/Portable/interface/PortableCollection.h"
#include "DataFormats/Portable/interface/PortableHostCollection.h"

using Phase2ITModuleMapHost = PortableHostCollection2<Phase2ITModuleMapSoA, Phase2ITFedMapSoA>;

#endif  // DataFormats_Phase2ITBitStreamSoA_interface_Phase2ITModuleMapHost_h
